version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  api: &api
    build: api
    tty: true
    stdin_open: true
    command: bash start.sh
    volumes:
      - ./api:/api
    ports:
      - 3030:3030
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db

  client: &client
    build: client
    command: bash start-client.sh
    tty: true
    stdin_open: true
    volumes:
      - ./client:/var/www/html
    ports:
      - 3000:3000
    depends_on:
      - api
  
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
